"""empty message

Revision ID: 89f73534d1ca
Revises: 
Create Date: 2024-05-28 02:05:16.069511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89f73534d1ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_management_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('time',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('send_addr',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('userID',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('recv_addr',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('messagecategory',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('sum',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('attached',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.drop_column('ID')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('recv_addr', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recv_serv', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recv_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recv_pwd', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('send_addr', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('send_serv', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('send_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('send_pwd', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('send_pwd')
        batch_op.drop_column('send_port')
        batch_op.drop_column('send_serv')
        batch_op.drop_column('send_addr')
        batch_op.drop_column('recv_pwd')
        batch_op.drop_column('recv_port')
        batch_op.drop_column('recv_serv')
        batch_op.drop_column('recv_addr')
        batch_op.drop_column('join_time')

    with op.batch_alter_table('mail_management_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('attached',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('sum',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('messagecategory',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('recv_addr',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('nickname',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('userID',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('send_addr',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('mail_id')

    # ### end Alembic commands ###
